.idea/misc.xml, app/build.gradle, app/src/main/java/com/example/myjavaapplication/LoginActivity.java, app/src/main/res/drawable/login_button_box.xml, app/src/main/res/drawable/login_sns_button_box.xml, app/src/main/res/drawable/login_sns_line.xml, app/src/main/res/layout/login_page.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
=> feat: 로그인기능

.idea/kotlinc.xml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/myjavaapplication/JoinActivity.java, app/src/main/java/com/example/myjavaapplication/LoginActivity.java, app/src/main/java/com/example/myjavaapplication/MainActivity.java, app/src/main/java/com/example/myjavaapplication/UserMedia.java, app/src/main/res/drawable/join_toggle.xml, app/src/main/res/drawable/join_toggle_mem.xml, app/src/main/res/drawable/join_toggle_pro.xml, app/src/main/res/drawable/join_write_box.xml, app/src/main/res/drawable/member_checkbox.xml, app/src/main/res/drawable/professional_clicked_drawable.xml, app/src/main/res/drawable/professional_icon.xml, app/src/main/res/drawable/professional_unclicked_drawable.xml, app/src/main/res/layout/fragment_mypage.xml, app/src/main/res/layout/join_page.xml, app/src/main/res/layout/login_page.xml, app/src/main/res/layout/mypet_info_item_layout.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
=> fix: 로그인페이지 수정

app/build.gradle, app/src/main/java/com/example/myjavaapplication/JoinActivity.java, app/src/main/java/com/example/myjavaapplication/LoginActivity.java
=> fix: 서버에러부분삭제

app/src/main/java/com/example/myjavaapplication/JoinActivity.java, app/src/main/java/com/example/myjavaapplication/LoginActivity.java, app/src/main/res/drawable/email_verfify_button_box.xml, app/src/main/res/layout/join_page.xml
회원 가입시에 이메일 인증 메일이 보내지지 않는 에러 수정 완료했습니다.
=> 회원가입 기능 이메일 인증 오류 수정

app/src/main/res/layout/fragment_mypage.xml
=> fix: mypage xml뭉개짐 현상 해결

app/build.gradle, app/src/main/java/com/example/myjavaapplication/JoinActivity.java, app/src/main/java/com/example/myjavaapplication/LoginActivity.java, app/src/main/java/com/example/myjavaapplication/MainActivity.java, app/src/main/java/com/example/myjavaapplication/MypageFragment.java, app/src/main/java/com/example/myjavaapplication/UserMedia.java, app/src/main/res/layout/fragment_mypage.xml, app/src/main/res/layout/join_page.xml, app/src/main/res/layout/login_page.xml, app/src/main/res/layout/mypet_info_item_layout.xml
=> fix: 데이터반영

app/src/main/java/com/example/myjavaapplication/MypageFragment.java
=> fix: image에러수정

.idea/.name, .idea/gradle.xml, .idea/misc.xml, app/src/main/res/drawable/petbox.xml, app/src/main/res/layout/fragment_petmanage.xml
=> feat: 펫관리페이지

app/src/main/res/drawable/petmanagementlook_box.xml, app/src/main/res/layout/fragment_petmanage.xml
완성했어요! 칼로리 부분 너무 좁아서 배열 안맞는거 죄송합니다..! 위쪽에 있는 것도 죄송해요! 알려주시면 수정하겠습니다
=> feat: 펫관리페이지완성

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/myjavaapplication/DaywalkActivity.java, app/src/main/res/layout/daywalk_page.xml
=> feat: daywalk

app/src/main/java/com/example/myjavaapplication/PetAdd2Activity.java, app/src/main/java/com/example/myjavaapplication/PetVaccineAdapter.java, app/src/main/java/com/example/myjavaapplication/PetVaccineSelectedDialog.java, app/src/main/res/layout/petadd2_page.xml
=> feat: pet 추가하는 페이지 완성

app/src/main/java/com/example/myjavaapplication/JoinActivity.java, app/src/main/java/com/example/myjavaapplication/LoginActivity.java
feat: 구글 로그인(일반회원가능)/일반로그인(일반,의사)
=> feat: 구글 로그인(일반회원가능)/일반로그인(일반,의사)

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/myjavaapplication/MonthWalkActivity.java, app/src/main/java/com/example/myjavaapplication/PetMedia.java, app/src/main/res/layout/daywalk_page.xml, app/src/main/res/layout/login_page.xml, app/src/main/res/layout/monthwalk_page.xml, app/src/main/res/layout/petstatus_page.xml, app/src/main/res/values/strings.xml
=> feat: 펫관리 달력페이지

app/src/main/java/com/example/myjavaapplication/JoinActivity.java, app/src/main/java/com/example/myjavaapplication/LoginActivity.java, app/src/main/java/com/example/myjavaapplication/MypageFragment.java, app/src/main/java/com/example/myjavaapplication/PetAdd2Activity.java, app/src/main/java/com/example/myjavaapplication/PetAddActivity.java, app/src/main/java/com/example/myjavaapplication/PetMedia.java, app/src/main/java/com/example/myjavaapplication/PetStatusFragment.java, app/src/main/java/com/example/myjavaapplication/UserMedia.java, app/src/main/res/layout/petstatus_page.xml
=> feat: 펫추가 데이터베이스연동

app/src/main/java/com/example/myjavaapplication/LoginActivity.java, app/src/main/java/com/example/myjavaapplication/PetmanageFragment.java, app/src/main/res/layout/fragment_petmanage.xml, app/src/main/res/layout/monthwalk_page.xml
=> feat : 달력산책레이아웃파일

app/src/main/java/com/example/myjavaapplication/HomeFragment.java
=> feat : homeFragment수정

app/src/main/res/layout/daywalk_page.xml
=> feat : daywalk_page수정

app/src/main/java/com/example/myjavaapplication/PetStatusFragment.java
=> feat: petstatuspage완성

app/src/main/res/layout/hosipital_page.xml
=> feat: 병원 등록하기 페이지 완료

.idea/misc.xml, app/src/main/java/com/example/myjavaapplication/LoginActivity.java, app/src/main/java/com/example/myjavaapplication/MainActivity.java, app/src/main/java/com/example/myjavaapplication/MypageFragment.java, app/src/main/java/com/example/myjavaapplication/PetmanageFragment.java, app/src/main/res/layout/fragment_home.xml
=> feat: home Fragment

app/src/main/java/com/example/myjavaapplication/PetmanageFragment.java
=> feat: petmanageFragment.java에서 11월월로 되어있길래 11월로 바꿨씁니다.

app/src/main/java/com/example/myjavaapplication/HomeFragment.java, app/src/main/java/com/example/myjavaapplication/PetmanageFragment.java, app/src/main/res/layout/fragment_petmanage.xml
=> feat : petManageMent수정사항 추가

app/src/main/java/com/example/myjavaapplication/HomeFragment.java, app/src/main/java/com/example/myjavaapplication/PetmanageFragment.java, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_mypage.xml, app/src/main/res/layout/fragment_petmanage.xml
=> feat : 레이아웃 수정 및 내용 변경

app/src/main/java/com/example/myjavaapplication/HomeFragment.java, app/src/main/java/com/example/myjavaapplication/JoinActivity.java, app/src/main/java/com/example/myjavaapplication/LoginActivity.java, app/src/main/java/com/example/myjavaapplication/MainActivity.java, app/src/main/java/com/example/myjavaapplication/MypageFragment.java, app/src/main/java/com/example/myjavaapplication/PetAddActivity.java, app/src/main/java/com/example/myjavaapplication/WalkRecordData.java, app/src/main/res/layout/fragment_home.xml
feat : walkData리스트, 심박수 클라우드 저장
=> feat : walkData리스트, 심박수 클라우드 저장

app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_mypage.xml, app/src/main/res/layout/fragment_petmanage.xml
=> feat : layout 수정

app/src/main/java/com/example/myjavaapplication/DaywalkActivity.java, app/src/main/java/com/example/myjavaapplication/HomeFragment.java, app/src/main/java/com/example/myjavaapplication/PetmanageFragment.java, app/src/main/res/layout/daywalk_page.xml, app/src/main/res/layout/fragment_petmanage.xml, app/src/main/res/layout/fragment_petstatus.xml
=> feat : 블루투스 테스트

app/src/main/java/com/example/myjavaapplication/PetmanageFragment.java
=> feat : layout 재수정!

.idea/misc.xml, app/build.gradle, app/src/main/java/com/example/myjavaapplication/MypageFragment.java, app/src/main/java/com/example/myjavaapplication/PetAdd2Activity.java, app/src/main/java/com/example/myjavaapplication/PetAddActivity.java
=> feat : 마이페이지 데이터 삭제 에러수정

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/myjavaapplication/Code.java, app/src/main/java/com/example/myjavaapplication/CommunityFragment.java, app/src/main/java/com/example/myjavaapplication/CommunityItemAdapter.java, app/src/main/java/com/example/myjavaapplication/CommunityItemData.java, app/src/main/java/com/example/myjavaapplication/CommunityLikeMedia.java, app/src/main/java/com/example/myjavaapplication/CommunityMedia.java, app/src/main/java/com/example/myjavaapplication/CommunityWriteActivity.java, app/src/main/java/com/example/myjavaapplication/HomeFragment.java, app/src/main/java/com/example/myjavaapplication/MainActivity.java, app/src/main/java/com/example/myjavaapplication/MypageFragment.java, app/src/main/res/drawable/comment_icon.xml, app/src/main/res/drawable/community_item_box.xml, app/src/main/res/drawable/create_icon.xml, app/src/main/res/drawable/filled_favorite_icon.xml, app/src/main/res/drawable/not_fill_favorite_icon.xml, app/src/main/res/drawable/photo_icon.xml, app/src/main/res/drawable/save_icon.xml, app/src/main/res/drawable/search_icon.xml, app/src/main/res/layout/community_item_layout.xml, app/src/main/res/layout/community_item_noimage_layout.xml, app/src/main/res/layout/community_write_page.xml, app/src/main/res/layout/fragment_community.xml, app/src/main/res/layout/fragment_mypage.xml, app/src/main/res/menu/main_navigation_menu.xml, app/src/main/res/values/colors.xml
=> feat : 커뮤니티 코딩

.idea/deploymentTargetDropDown.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/myjavaapplication/CommentItemAdapter.java, app/src/main/java/com/example/myjavaapplication/CommentItemData.java, app/src/main/java/com/example/myjavaapplication/CommentMedia.java, app/src/main/java/com/example/myjavaapplication/CommunityFragment.java, app/src/main/java/com/example/myjavaapplication/CommunityReadActivity.java, app/src/main/java/com/example/myjavaapplication/CommunityWriteActivity.java, app/src/main/java/com/example/myjavaapplication/PetmanageFragment.java, app/src/main/res/drawable/cancel_icon.xml, app/src/main/res/drawable/comment_item_box.xml, app/src/main/res/drawable/file_icon.xml, app/src/main/res/drawable/friend_icon.xml, app/src/main/res/drawable/mypage_click_icon.xml, app/src/main/res/layout/comment_item_layout.xml, app/src/main/res/layout/community_read_page.xml, app/src/main/res/layout/community_write_page.xml, app/src/main/res/layout/fragment_community.xml, app/src/main/res/layout/fragment_mypage.xml
=> feat : 커뮤니티 기능 추가

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/example/myjavaapplication/PetmanageFragment.java
=> feat : 에러 수정

app/src/main/java/com/example/myjavaapplication/CommunityFragment.java, app/src/main/java/com/example/myjavaapplication/CommunityReadActivity.java, app/src/main/java/com/example/myjavaapplication/MypageCommunityAdapter.java, app/src/main/java/com/example/myjavaapplication/MypageCommunityDialog.java, app/src/main/java/com/example/myjavaapplication/MypageFragment.java, app/src/main/java/com/example/myjavaapplication/PetmanageFragment.java, app/src/main/res/drawable/mycommunity_box.xml, app/src/main/res/layout/dialog_mycommunity.xml, app/src/main/res/layout/mypagecommunity_item_layout.xml, app/src/main/res/layout/mypagecommunity_item_noimage_layout.xml
=> feat : 에러 수정(커뮤키티 좋아요 관련)

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/example/myjavaapplication/DaywalkActivity.java, app/src/main/java/com/example/myjavaapplication/LoginActivity.java, app/src/main/java/com/example/myjavaapplication/MainActivity.java, app/src/main/java/com/example/myjavaapplication/MypageFragment.java, app/src/main/java/com/example/myjavaapplication/MypageFriendDialog.java, app/src/main/java/com/example/myjavaapplication/NameChangeDialog.java, app/src/main/res/drawable/walk_status_button_box.xml, app/src/main/res/layout/dialog_setname.xml, app/src/main/res/layout/fragment_mypage.xml
=> feat : 마이페이지 레이아웃수정

app/src/main/java/com/example/myjavaapplication/CommunityReadActivity.java
=> feat : 커뮤니티좋아요 db 수정
